Settings page
paritytech/contracts-ui pull request #214
Opened 2022-02-22 20:04 UTC by statictype

settings page with theme select
css changes for light theme

if there is no "theme" key in local storage, it uses system preference for dark mode
there is a bit of FOUC if you are on dark mode and you reload the page

2022-02-23 00:29 UTC, kwingram25 commented on src/ui/templates/Page.tsx
> +                <div className="py-2 align-middle inline-block min-w-full h-full sm:px-6 lg:px-8 mt-4">
Seeing an unnecessary scrollbar on the page, removing h-full here removes it.

2022-02-23 00:30 UTC, kwingram25 requested changes
In light mode the status indicator spinner appears to still be white and invisible against the background. Everything else looks great!

2022-02-24 11:37 UTC, erler commented
Looks good! Besides the white spinner, I noticed that some links aren't blue (eg. Using Estimated Gas  ·  Use Custom toggle, or the "Learn more" link on the card). But otherwise great and we can always fix small styling things later.

2022-02-24 23:20 UTC, kwingram25 submitted a review, later dismissed

2022-02-28 02:19 UTC, kwingram25 approved these changes

2022-02-28 02:19 UTC, merged