Vite correction
paritytech/contracts-ui pull request #281
Opened 2022-04-06 23:29 UTC by kwingram25

2022-04-12 10:09 UTC, statictype requested changes

2022-04-12 10:09 UTC, statictype commented on package.json
> -    "prepare": "husky install"
looks like we need `postinstall` here https://typicode.github.io/husky/#/?id=yarn-2
assuming the instructions are for yarn 2+

2022-04-12 20:06 UTC, kwingram25 commented on src/ui/index.tsx
> +globalThis.Buffer = Buffer;
Not included by default. https://github.com/vitejs/vite/discussions/3126#discussioncomment-655531

2022-04-12 20:09 UTC, kwingram25 commented on tsconfig.node.json
> +{
This is how the default scaffolded project looks. I can't find why it is done this way but not necessary it seems

2022-04-13 13:09 UTC, statictype approved these changes

2022-04-13 13:09 UTC, merged