Added more options to Testnets and Production newworks
paritytech/contracts-ui pull request #417
Opened 2023-02-27 14:23 UTC by Yasir761

2023-02-27 15:09 UTC, statictype requested changes

2023-02-28 07:36 UTC, cmichi commented
Testnets should be named like this:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/241530/221784973-eafba570-107f-41d4-9cb9-9c5f52f8fe80.png">

For Phala it's "Phala Development" and the RPC is `poc5.phala.network`.

2023-02-28 07:39 UTC, cmichi commented on src/constants/index.ts
> +  PHALA = 'wss://khala.phala.network/ws',
Line 9

2023-02-28 17:36 UTC, Yasir761 commented on src/ui/components/sidebar/NetworkAndUser.tsx
> +        value={endpoint}
Ok, I will make change

2023-03-01 07:34 UTC, Yasir761 commented on src/ui/components/sidebar/NetworkAndUser.tsx
> +        value={endpoint}
I made a change but it showing error : value={options.find((o) => o.value === endpoint)?.value || RPC.CONTRACTS}
![Screenshot 2023-03-01 130400](https://user-images.githubusercontent.com/74600745/222073568-f513cbd0-b17e-4e0a-b677-a82c06e145e3.png)

2023-03-16 07:13 UTC, closed without merging